# schema.yml
 version: 2
 sources:
   - name: gz_raw_data
     tables:
       - name: raw_gz_sales
         description: sales of Greenweez / we have on row per product_id found in each orders_id
         columns:
           - name: date_date
             description: date of purchase
        # Freshness testing - make sure to fill in the ...
         loaded_at_field: "CAST(date_date AS TIMESTAMP)"
         freshness:
           warn_after: {count : 90, period : day }
       - name: raw_gz_product
         description: product of Greenweez / we have one row per product_id and its price
         columns:
           - name: products_id
             description: id of the product
             tests :
                - unique
                - not_null
       - name: raw_gz_ship
         description: ship of Greenweez / we have one row per product_id and shipping info
         columns:
           - name: orders_id
             description: id of the order
             tests :
                - unique
                - not_null        
       - name: raw_gz_adwords
         description: adwords
       - name: raw_gz_bing
         description: bing
       - name: raw_gz_criteo
         description: criteo  
       - name: raw_gz_facebook
         description: facebook
         